-- src/audio.lua: Sound effect loader and playback helpers.
--
-- Audio files are generated by tools/generate_sfx.py and live in assets/sfx/.
-- If a file is missing or love.audio is unavailable, all play calls are no-ops.

local Audio = {}

local VOLUME = 0.7

local function tryLoad(path)
    local ok, src = pcall(love.audio.newSource, path, "static")
    if ok then
        src:setVolume(VOLUME)
        return src
    end
    return nil
end

function Audio.load()
    Audio.sfx = {
        kick       = tryLoad("assets/sfx/kick.wav"),
        bounce     = tryLoad("assets/sfx/bounce.wav"),
        substitute = tryLoad("assets/sfx/substitute.wav"),
        whistle    = tryLoad("assets/sfx/whistle.wav"),
        goal       = tryLoad("assets/sfx/goal.wav"),
    }
end

local function play(name)
    local src = Audio.sfx and Audio.sfx[name]
    if src then
        src:stop()
        src:play()
    end
end

function Audio.playKick()       play("kick") end
function Audio.playBounce()     play("bounce") end
function Audio.playSubstitute() play("substitute") end
function Audio.playWhistle()    play("whistle") end
function Audio.playGoal()       play("goal") end

return Audio
